onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group Testbench /tb_gddr_ref_design/clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/reset_n
add wave -noupdate -group Testbench /tb_gddr_ref_design/chip_ready
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_start
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_fail
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_fail_d
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_timeout
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_complete
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_aresetn
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_bvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_bresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_bid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awaddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wstrb
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_araddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_bready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_aresetn
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_bvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_bresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_bid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awaddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wstrb
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_araddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_bready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_aresetn
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_bvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_bresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_bid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awaddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wstrb
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_araddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_bready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_aresetn
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_bvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_bresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_bid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awaddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wstrb
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_araddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_bready
add wave -noupdate -group Testbench /tb_gddr_ref_design/pll_lock
add wave -noupdate -group Testbench /tb_gddr_ref_design/pll_gddr_NE_lock
add wave -noupdate -group Testbench /tb_gddr_ref_design/pll_gddr_NW_lock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/i_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/i_reset_n
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/i_start
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/pll_lock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/pll_gddr_NE_lock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/pll_gddr_NW_lock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_aresetn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_bvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_bresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_bid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_aresetn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_bvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_bresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_bid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_aresetn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_bvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_bresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_bid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_aresetn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_bvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_bresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_bid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awaddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wstrb
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_araddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_bready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awaddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wstrb
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_araddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_bready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awaddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wstrb
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_araddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_bready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awaddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wstrb
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_araddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_bready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/o_fail
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/o_fail_oe
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/o_xact_done
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/o_xact_done_oe
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/nap_fail
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/dci_fail
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/nap_done
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/dci_done
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/cfg_wr_rdn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/poll_ptr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/cfg_addr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/cfg_req
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/cfg_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/cfg_ack
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr_ready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/poll_state
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/rstn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/dci_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/dci_input_rstn
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1101000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 234
configure wave -valuecolwidth 235
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {38481450 ps}
