onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate -group Testbench /tb_gddr_ref_design/clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/reset_n
add wave -noupdate -group Testbench /tb_gddr_ref_design/chip_ready
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_start
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_fail
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_fail_d
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_timeout
add wave -noupdate -group Testbench /tb_gddr_ref_design/test_complete
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_aresetn
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_bvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_bresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_bid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awaddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_awsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wstrb
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_wlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_araddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_arsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_rready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_1_dc0_bready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_aresetn
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_bvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_bresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_bid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awaddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_awsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wstrb
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_wlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_araddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_arsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_rready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_2_dc0_bready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_aresetn
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_bvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_bresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_bid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awaddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_awsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wstrb
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_wlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_araddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_arsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_rready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_5_dc0_bready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_clk
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_aresetn
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_bvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_bresp
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_bid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awcache
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awprot
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awaddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_awsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wdata
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wstrb
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_wlast
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arvalid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_araddr
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arlen
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arid
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arqos
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arburst
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arlock
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_arsize
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_rready
add wave -noupdate -group Testbench /tb_gddr_ref_design/gddr6_6_dc0_bready
add wave -noupdate -group Testbench /tb_gddr_ref_design/pll_lock
add wave -noupdate -group Testbench /tb_gddr_ref_design/pll_gddr_NE_lock
add wave -noupdate -group Testbench /tb_gddr_ref_design/pll_gddr_NW_lock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/i_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/i_reset_n
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/i_start
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/pll_lock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/pll_gddr_NE_lock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/pll_gddr_NW_lock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_aresetn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_bvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_bresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_bid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_aresetn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_bvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_bresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_bid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_aresetn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_bvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_bresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_bid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_aresetn
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_bvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_bresp
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_bid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awaddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wstrb
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_wlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_araddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_rready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_bready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_arprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_1_dc0_awprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awaddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wstrb
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_wlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_araddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_rready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_bready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_arprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_2_dc0_awprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awaddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wstrb
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_wlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_araddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_rready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_bready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_arprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_5_dc0_awprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awaddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wdata
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wstrb
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_wlast
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arvalid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_araddr
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arlen
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arid
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arqos
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arburst
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arlock
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arsize
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_rready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_bready
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awcache
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_arprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/gddr6_6_dc0_awprot
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/o_fail
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/o_xact_done
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/nap_fail
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/dci_fail
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/nap_done
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/dci_done
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/dci_clk
add wave -noupdate -group DUT /tb_gddr_ref_design/DUT/dci_input_rstn
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awvalid}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awready}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awaddr}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awlen}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awid}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awqos}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awburst}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awlock}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awsize}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awregion}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awprot}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/awcache}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/wvalid}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/wready}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/wdata}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/wstrb}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/wlast}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arready}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/rdata}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/rlast}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/rresp}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/rvalid}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/rid}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/araddr}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arlen}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arid}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arqos}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arburst}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arlock}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arsize}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arvalid}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arregion}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arprot}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/arcache}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/rready}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/bvalid}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/bready}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/bresp}
add wave -noupdate -group {NAP[0]} {/tb_gddr_ref_design/DUT/gddr_gen_noc[0]/noc_on/nap/bid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awvalid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awready}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awaddr}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awlen}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awqos}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awburst}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awlock}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awsize}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awregion}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awprot}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/awcache}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/wvalid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/wready}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/wdata}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/wstrb}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/wlast}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arready}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/rdata}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/rlast}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/rresp}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/rvalid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/rid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/araddr}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arlen}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arqos}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arburst}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arlock}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arsize}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arvalid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arregion}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arprot}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/arcache}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/rready}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/bvalid}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/bready}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/bresp}
add wave -noupdate -group {DCI[0]} {/tb_gddr_ref_design/DUT/gddr_gen_dci[0]/dci_on/dci/bid}
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {1101000 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 234
configure wave -valuecolwidth 235
configure wave -justifyvalue left
configure wave -signalnamewidth 1
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ps} {6101813 ps}
