
# -----------------------------------------------
# Autogenerated simulation filelist
# Do not edit this file as it will be overwritten
# Generated by D:/questasim64_10.7c/win64/../tcl/vsim/vsim on 11:22:59 Tue 02 Nov 21
# -----------------------------------------------


# Configure verilog libraries to look for modules
# using their extension
+libext+.v
+libext+.sv


# -------------------------------------
# Filelist added files from ../../src/filelist.tcl
# -------------------------------------

# Verilog design file include directory
+incdir+../../src/include
# Verilog testbench file include directory
+incdir+../../src/tb

# Verilog source files
../../src/rtl/default_nettype.v
-sv ../../src/rtl/random_seq_engine.sv
-sv ../../src/rtl/axi_pkt_gen.sv
-sv ../../src/rtl/axi_pkt_chk.sv
-sv ../../src/rtl/nap_slave_wrapper.sv
-sv ../../src/rtl/reset_processor.sv
-sv ../../src/rtl/axi_nap_csr_master_ddr.sv
-sv ../../src/rtl/ddr4_training_polling_block.sv
-sv ../../src/rtl/ddr4_ref_design_top.sv

# Verilog testbench files
-sv ../../src/tb/tb_noc_memory_behavioural.sv
-sv ../../src/tb/tb_ddr4_ref_design.sv

# -------------------------------------
# End of user filelist ../../src/filelist.tcl
# -------------------------------------




