
# -----------------------------------------------
# Autogenerated simulation filelist
# Do not edit this file as it will be overwritten
# Generated by D:/questasim64_10.7c/win64/../tcl/vsim/vsim on 14:43:30 Tue 02 Nov 21
# -----------------------------------------------

# Simulation filelist template


# Speed up simulations
+define+SIMSTEP_RTL

# Library paths
+incdir+$ACE_INSTALL_DIR/libraries

# Configure verilog libraries to look for modules
# using their extension
+libext+.v
+libext+.sv

# Include IP models
# $ACE_INSTALL_DIR/libraries/device_models/7t_simmodels.v
$ACE_INSTALL_DIR/libraries/device_models/AC7t1500ES0_simmodels.sv 


# -------------------------------------
# Filelist added files from ../../src/filelist_b60.tcl
# -------------------------------------

# Verilog design file include directory
+incdir+../../src/include
# Verilog testbench file include directory
+incdir+../../src/tb

# Verilog source files
../../src/rtl/default_nettype.v
-sv ../../src/rtl/mlp_wrapper_multi.sv
-sv ../../src/rtl/dot_product_16_8x8_multi.sv
-sv ../../src/rtl/nap_slave_wrapper.sv
-sv ../../src/rtl/dataflow_control.sv
-sv ../../src/rtl/line_fifo.sv
-sv ../../src/rtl/out_fifo.sv
-sv ../../src/rtl/reset_processor.sv
-sv ../../src/rtl/mlp_conv2d_top.sv

# Verilog testbench files
-sv ../../src/tb/tb_mlp_behavioural_16x_int8.sv
-sv ../../src/tb/tb_axi_mem_checker.sv
-sv ../../src/tb/tb_noc_memory_behavioural.sv
-sv ../../src/tb/tb_mlp_conv2d.sv

# -------------------------------------
# End of user filelist ../../src/filelist_b60.tcl
# -------------------------------------





